# basic options
title: Charlie's Bagels
author: Charlie's Bagels
email: hello@charliesbagels.com
description: Welcome to the Charlie's Bagels website! Home of the world famous Charlie's Bagels!
twitter_username: CharliesBagels
github_username:  CharliesBagels

# Build settings
markdown: kramdown
theme: minima
